apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-server-lb
  name: grpc-server-lb-metrics
  namespace: default
spec:
  ports:
  - port: 1234
    protocol: TCP
    targetPort: 1234
  selector:
    app: grpc-server-lb
  type: LoadBalancer
